version: '3.8'
services: 
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "5673:5673"
      - "15672:15672"
  interest:
    build: ./worker
    ports:
      - "8000:8080"
    environment:
    - APP_VERSION=1.0 
    depends_on:
      - rabbit 
    volumes:
    - type: bind
      source: ./compose/labels.production
      target: /app/labels                
  interest-preview:
    build: ./worker
    ports:
      - "9000:8080"
    environment:
    - APP_VERSION=2.0 
    depends_on:
      - rabbit    
    volumes:
    - type: bind
      source: ./compose/labels.preview
      target: /app/labels       